"""Provenance and taint labels.

Taint tracking here follows the classic *information-flow* lattice with two
points: ``TRUSTED`` < ``UNTRUSTED``. Joining two labels yields the least upper
bound, so once any untrusted input contributes to a value, the result is
untrusted forever ("taint is sticky"). There is deliberately **no** operation
that lowers a label: the only way untrusted data reaches a sink is through an
explicit, audited policy decision in the reference monitor.
"""

from __future__ import annotations

import enum
from collections.abc import Iterable
from dataclasses import dataclass, field

__all__ = ["Provenance", "Trust"]


class Trust(enum.Enum):
    """Integrity level of a value."""

    TRUSTED = "trusted"
    """Authored by the operator or the authenticated user (or derived only from such data)."""

    UNTRUSTED = "untrusted"
    """Originates, even partially, from an external party: tool output, web, e-mail, MCP metadata."""

    def join(self, other: Trust) -> Trust:
        """Least upper bound in the integrity lattice (untrusted dominates)."""
        if self is Trust.UNTRUSTED or other is Trust.UNTRUSTED:
            return Trust.UNTRUSTED
        return Trust.TRUSTED


@dataclass(frozen=True, slots=True)
class Provenance:
    """Immutable description of where a value came from.

    Attributes:
        trust: Integrity level of the value.
        sources: Symbolic names of every origin that influenced the value, e.g.
            ``"tool:read_inbox"``, ``"llm:quarantined"``, ``"user"``. Source names
            are generated by trusted code only and never contain untrusted text.
        derived_from: Tokens of the symbolic pointers the value was computed from.
    """

    trust: Trust
    sources: frozenset[str]
    derived_from: frozenset[str] = field(default_factory=frozenset)

    def __post_init__(self) -> None:
        if not self.sources:
            raise ValueError("Provenance requires at least one source")

    @classmethod
    def trusted(cls, source: str) -> Provenance:
        """Provenance for data authored by the user or the operator."""
        return cls(Trust.TRUSTED, frozenset({source}))

    @classmethod
    def untrusted(cls, source: str) -> Provenance:
        """Provenance for data coming from an external, potentially hostile, party."""
        return cls(Trust.UNTRUSTED, frozenset({source}))

    @property
    def is_untrusted(self) -> bool:
        """``True`` if any untrusted input contributed to the value."""
        return self.trust is Trust.UNTRUSTED

    def join(self, others: Iterable[Provenance], *, extra_source: str | None = None) -> Provenance:
        """Combine this label with ``others`` (taint propagation).

        Args:
            others: Labels of the other inputs of a computation.
            extra_source: Optional name of the computation itself (e.g. ``"llm:quarantined"``).

        Returns:
            A new label whose trust is the lattice join and whose sources/lineage
            are the union of all inputs.
        """
        trust = self.trust
        sources = set(self.sources)
        derived = set(self.derived_from)
        for other in others:
            trust = trust.join(other.trust)
            sources |= other.sources
            derived |= other.derived_from
        if extra_source is not None:
            sources.add(extra_source)
        return Provenance(trust, frozenset(sources), frozenset(derived))

    def with_lineage(self, tokens: Iterable[str]) -> Provenance:
        """Return a copy with ``tokens`` added to :attr:`derived_from`."""
        return Provenance(self.trust, self.sources, self.derived_from | frozenset(tokens))
